# Demo Catalog metadata — parsed by sync agent
title: Project Million
pitch: AI-powered business acquisition intelligence platform for discovering, analyzing, and structuring small business deals
status: draft
category: fintech
platform: lovable
featured: false
demo_video:
cover_prompt: A sophisticated dark dashboard showing business acquisition analytics with glowing data visualizations, capital stack diagrams, and AI-powered deal scoring metrics
